# general settings
name: train_CGA_x2_P64_B4G1
model_type: CGAModel
scale: 2
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: AIDTrain
    type: PairedImageDataset
    dataroot_gt: ~ # provide / path / to / HR
    dataroot_lq: ~ # provide / path / to / LRx2
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: AIDVal
    type: PairedImageDataset
    dataroot_gt: ~ # provide / path / to / HR
    dataroot_lq: ~ # provide / path / to / LRx2
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: CGA
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  mlp_ratio: 2
  resi_connection: '1conv'
  split_size: [8,32]
  c_ratio: 0.5

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500